### ISSUE TITLE
Support for using IAM role in stream loader deployment

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/charts#114]
**Is your feature request related to a problem? Please describe.**
Hi, this is Sreenath from Whitepages. We use IAM roles to provide access to AWS resources(via kube2iam) in our helm deployments. Would greatly make our process easier if you could support them in your helm charts. Currently we only require this in the stream-loader helm chart
(https://github.com/Senzing/charts/blob/master/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml)

**Describe the solution you'd like**
Please add the following to deployment.yaml under `spec->template->metadata` section with the new `annotations` heading being on same level as lables (below this line: https://github.com/Senzing/charts/blob/master/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L17)
```
annotations:
{{- if .Values.awsRole }}
  iam.amazonaws.com/role: {{ .Values.awsRole | quote }}
{{- end }}
```
NOTE: The if check can be moved above to include `annotations` also under it, if there are no other annotations.

add a default value in values.yaml(https://github.com/Senzing/charts/blob/master/charts/senzing-stream-loader/senzing-stream-loader/values.yaml) so that users know there is support for IAM role
```
awsRole: ""
```
If value is empty , it will not get used in deployment. If a user specifies a value in their values file, it will be used in the deployment.yaml

**Comment by docktermj** [comment]
@ssasidharanwp  I'm pondering a slightly more generalized approach to the issue you illuminated.   I'm thinking in terms of allowing a user to specify any annotations.   Here's the approach:

A deployment would have the following changes:

1. https://github.com/Senzing/charts/blob/55675df1f8238a2c44c6e316022d408c90665430/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L7-L10
1. https://github.com/Senzing/charts/blob/55675df1f8238a2c44c6e316022d408c90665430/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L22-L25

Then annotations could be made in a `values.yaml` file like this:

```yaml
spec:
  template:
    annotations:
      iam.amazonaws.com/role: my-aws-role
      bobs/role: a-role-by-bob
```

Do you see any flaw in this approach?

**Comment by ssasidharanwp** [comment]
I think that is a good idea. I dont see any problems with that. I dont have a good knowledge of helm control structures. So I dont understand why you have used `if` at one place and `with` at the other place for the annotations. If that is intended then it is fine

**Comment by docktermj** [comment]
From what I can tell, the major difference between `if` and `with` is that the context inside of `with` can be simplified to a period (`.`) because of scoping.

References:
1. https://helm.sh/docs/chart_template_guide/control_structures/#ifelse
1. https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with

**Comment by ssasidharanwp** [comment]
got it. thanks for the info

**Comment by docktermj** [comment]
@ssasidharanwp I realized that there are 2 places where annotations go, so I modified the approach slightly so that each can be specified independently.

A `values.yaml` file has this:

```yaml
https://github.com/Senzing/charts/blob/61306f4ae76e0d36045c79e884eb0705f5dba209/charts/senzing-stream-loader/senzing-stream-loader/values.yaml#L3-L9
```
Which is applied to
1. https://github.com/Senzing/charts/blob/61306f4ae76e0d36045c79e884eb0705f5dba209/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L7-L10
1. https://github.com/Senzing/charts/blob/61306f4ae76e0d36045c79e884eb0705f5dba209/charts/senzing-stream-loader/senzing-stream-loader/templates/deployment.yaml#L22-L25

The changes have been pulled into the master branch.

If this satisfies your request, please close the issue.  If it doesn't, please let us know what else we can improve on.

**Comment by ssasidharanwp** [comment]
Thank you !! I tried this change and it works for us. Appreciate the quick work on this !!
