### ISSUE TITLE
governor-postgresql-transaction-id variables not supported

### ISSUE THREAD

**Issue by dev-eng1** [Senzing/charts#180]
**Describe the solution you'd like**
Various modules, such as streamloader use a governor. Senzing provide a default governor for postgresql databases at https://github.com/Senzing/governor-postgresql-transaction-id. This can be configured using seven environment variables e.g. SENZING_GOVERNOR_POSTGRESQL_HIGH_WATERMARK. These cannot be configured using the current helm charts.

All helm charts for modules with governor support should be upgraded to support the governor configuration environment variables.

**Comment by docktermj** [comment]
Hi @dev-eng1 !

We recently updated our charts to be more in line with what I believe is one of the leaders in Helm Charting, Bitnami.  (Reference: https://github.com/bitnami/charts/)   Which has solved this problem -- I'll explain.

Since a "governor" is a plugin, there can be other governors besides the one provided by Senzing.   So it wouldn't be possible to anticipate all of the Environment Variables needed for any custom governor.  To keep a clean separation of programs like `stream-loader.py`and any plugin, we don't have specific helm values for any governor, including ours.

However!  The magic for passing in environment variables to any plugin can be seen at https://github.com/Senzing/charts/blob/f72eaa7efe46da58348e8472196955ce78800637/charts/senzing-stream-loader/values.yaml#L133-L139  It is  the default `values.yaml` file.

So in your `values.yaml` file you would want to pass in additional environment values like this:

```yaml
main:
  :
  extraEnvVars:
    - name: SENZING_GOVERNOR_POSTGRESQL_HIGH_WATERMARK
      value: 1000000000
    - name: SENZING_GOVERNOR_INTERVAL
      value: 6000
    :
```

Does that get you what you need?

**Comment by dev-eng1** [comment]
Probably. We haven't been able to upgrade our helm charts for a while as we're still waiting on the merge request for the license change! So when we came across this issue we just grep'ed for the variables.
Now I've got to port the license changes!
